### ISSUE TITLE
Crash with DJ 1st version

### ISSUE THREAD

**Issue by sutex** [Duke-Jones/RegulatedNoise#2]
Crash with DJ 1st version, worked for ages no problem , then it just didn't , 
https://www.dropbox.com/s/33f3mfh0d8lu0l2/RegulatedNoiseDump.7z?dl=0

NOW using the 1.8.4-0.0.3b , it started but gave me this  log file I clicked yes and RN started 
https://www.dropbox.com/s/fkz7lnvs0g0vorb/Exception_2015-02-10%2020-28-3877049e15-151e-4c7e-af37-99e008d14c52.log?dl=0

**Comment by Duke-Jones** [comment]
is your Captians log empty now ?  
If so, I have an idea what is the reason. 

Unfortunately I can't debug pre DJ002 versions  - yours is 001,  right?

**Comment by sutex** [comment]
Was now is 002, but i do have some information in there , had to hit the edit button to get it in there , but quite happy to start fresh if it will work right

**Comment by Duke-Jones** [comment]
Hm, it' strange. The problem was an invalid entry in a original ED-File:

Errorfile:
%DangerousDir%\Products\FORC-FDEV-D-1003\AppConfig.xml

Errormessage:
"The '=' character, hexadecimal value 0x3D, cannot be included in a name. Line 19, position 30."

Thats not really a RN problem but I  can not explain why this is so and whats the reason ?!?
really really strange :-?

**Comment by Duke-Jones** [comment]
fixed in v1.84-0.03 release
