### ISSUE TITLE
How to submit Forked changes for review

### ISSUE THREAD

**Issue by codersparks** [Duke-Jones/RegulatedNoise#80]
Hi, I have recently forked RegulatedNoise as I would like to have a go at improving the webserver side of things. So far I have made the following changes:
1. Created an interface from the previous WebServer
2. Where the coder referred to the previous WebServer it now uses a WebServerAdapter
3. User can select webserver to use on the "Webserver" tab (this is also propagated to the RegulatedNoiseSettings).
4. Moved the previous Webserver to be SimpleWebServer and created a BootstrapWebServer from which I plan on creating a new Webserver using [Bootstrap](http://getbootstrap.com/2.3.2/) to make it look a little prettier (choose this as I think this will be more simple that implementing different functionality) - Currently this just changes the title on the home page from "RegulatedNoise" to "Bootstrap RegulatedNoise" just so that I could test the changes I made

My plan then would be to try and fix the "Add note" functionality moving it out into helper classes so that the functionality can be separated from the webserver code (and allows the same code to be used in different webservers).

I am doing this to learn a bit of C# (having come from a Java background) and therefore am quite happy if it never gets back into the master branch/releases but if you feel you can accept the changes then so much the better. If you are willing to accept contributions can you let me know how I should submit these? 

Cheers

Codersparks

**Comment by Duke-Jones** [comment]
Hi,
sorry for the late response. 
It's interesting what you wan't  to do and maybe
I will merge your changes one day into the main branch. But I'm 
sorry, because for the moment I concentrate all time which 
I can spend (it's summer and so on..so it's not much ;-) ) on the sql-rebuild 
of RegulatedNoise.
As the past has shown it's absolute neccessary to check the changes in detail
and so I'm not more willing to add the changes blindly. In cause of this I will not 
accept any changes from other devs before the sql-rebuild is done.

btw: have you seen the pull request from alfeg ? 
see https://github.com/Duke-Jones/RegulatedNoise/pulls

You maybe can consider his changes, because I think they are interesting, too.

.... with the sql-rebuild will come extensive changes to the 
internal structure. Please have this in mind.

Duke

**Comment by codersparks** [comment]
Not a problem, this is for fun after all :)

I did see alfeg's pull request after I had played around and wrote my above comment and I will probably use that pull request as a new starting point.

One question I did have is, with your SQL rewrite are you changing any of the "api" that the webserver uses? or are you just rewriting the interactions with the DB?

If it is the first then I can work in parallel with you, if it is the latter then I will probably need to wait

**Comment by Duke-Jones** [comment]
As an example the structures in Form1 

```
    public CommandersLog CommandersLog;
    public ObjectDirectory StationDirectory = new StationDirectory();
    public ObjectDirectory CommodityDirectory = new CommodityDirectory();
    private EDMilkyway _Milkyway;
    (** and more**)
```

will be completely removed. 
Instead of them I will use dynamically loaded DataSets for ALL data. 
The sql structure is almost complete (see the sql branch https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL). There you can see, what kind of 
data is in the database. For investigation you can load the file "RNDatabase\SQL-Model\Elite_DB.mwb" with the MySQL Workbench (http://dev.mysql.com/downloads/workbench/). 

At the moment I'm implementing the upload of the old, existing data and from 
the files into the database (also updating systems and stations by actual EDDB files).
If this is done I will restructure the program itself.

**Comment by Duke-Jones** [comment]
closed due to focusing on MySQL branch (https://github.com/Duke-Jones/RegulatedNoise/tree/MySQL)
